targets = [ "//:dom" ]

[[dependency]]
package = "github.com/buckaroo-pm/netsurf-hubbub"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/netsurf-parserutils"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/netsurf-wapcaplet"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/xml2"
version = "branch=master"
